version: '3'

services:
    python:
        container_name: python_cpu
        build:
            context: .
            dockerfile: docker/cpu/Dockerfile
        volumes:
            - .:/usr/src
        tty: true
